name: Landing Compose CI

on:
  push:
    branches: [ "landing" ]
  pull_request:
    branches: [ "landing" ]

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clean docker
      run: docker image prune -f
    - name: Run server
      run: docker compose up --build -d